{ { - if .Values.serviceAccount.create - } }
apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "foo.serviceAccountName" . } }
  namespace: { { .Values.namespace } }
  labels:
    app: foo
    { { - include "foo.labels" . | nindent 4 } }
  { { - with .Values.serviceAccount.annotations } }
  annotations:
    { { - toYaml . | nindent 4 } }
  { { - end } }
  { { - end } }
