apiVersion: v1
kind: Service
metadata:
  name: { { include "foo.fullname" . } }
  namespace: { { .Values.namespace } }
  labels:
    app: foo
    { { - include "foo.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: foo
    { { - include "foo.selectorLabels" . | nindent 4 } }
